apiVersion: v1
kind: Service
metadata:
  name: docker-kube-sandbox
  labels:
    name: docker-kube-sandbox
spec:
  type: NodePort
  ports:
  - port: 4200
    protocol: TCP
    targetPort: 4200
  selector:
    name: docker-kube-sandbox
  sessionAffinity: ClientIP
